# Site settings
title: Cheese Dev
email: nezahrish@gmail.com
description: "cheese dev"
baseurl: ''
url: "http://cheddars.github.io"
signoff: 'soft cheese'

# Build settings
markdown: kramdown
permalink: /:title.html

disqus_shortname:disqus_VWoYmV5dCS 
facebook_appid:   
google_analytics: 

links:
  - name:         About
    url:          /about
  - name:         Facebook
    url:          
    external:     true
  - name:         GitHub
    url:          
    external:     true
