# Site settings
title: Blaze Boy
email: blazeeboy@gmail.com
description: "Software Engineer and Particularly a Ruby Addict"
baseurl: ''
url: "http://www.blazeboy.me"
signoff: 'E.E'

# Build settings
markdown: kramdown
permalink: /:title.html

disqus_shortname: blazeboy
facebook_appid:   1400091873588797
google_analytics: UA-53753121-1

links:
  - name:         About
    url:          /about
  - name:         Facebook
    url:          https://www.facebook.com/blazeeboy
    external:     true
  - name:         GitHub
    url:          https://github.com/blazeeboy
    external:     true